name: paywall
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.2
  injectable: ^2.5.0
  get_it: ^8.0.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
